spinnaker:
  modules:
    - orca
    - clouddriver

security:
  user:
    name: user
    password: password

multipart:
  max-file-size: 100Mb
  max-request-size: 100Mb

logging:
  level:
    reactor:
      core: DEBUG
    org:
      cloudfoundry: DEBUG
      springframework:
        web: TRACE
        cloud:
          deployer: DEBUG
